### ISSUE TITLE
Lateinit property not initialized

### ISSUE THREAD

**Issue by 1gn1t10n** [Kennyc1012/DashWeatherExtension#1]
Hi, thanks for the effort you put in the extension.

I haven't developed for Android or in Kotlin before. I built the application with my own OpenWeather API key and installed it with:
```
./gradlew build
adb install ./app/build/outputs/apk/debug/app-debug.apk
```

The extension is recognised by DashClock ([1.7.2](https://www.apkmirror.com/apk/roman-nurik-and-ian-lake/dashclock-widget/dashclock-widget-1-7-2-release/dashclock-widget-1-7-2-android-apk-download/)). Unfortunately, it crashes when opening the settings. Looking through the logs, I find:
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.kennyc.dashweather/com.kennyc.dashweather.SettingsActivity}: kotlin.UninitializedPropertyAccessException: lateinit property preferences has not been initialized
```
There are similar log entries for the other lateinit variables (`presenter`, `logger`).

I have tried on a phone with Android 8 and one with Android 11. Same results. I couldn't find any other hints in the README.

Before digging deeper into Kotlin, Dagger and Android development in general, I wanted to check with you what was the most recent environment in which the extension built and ran succesfully.

Any pointers in the right direction are appreciated. Thanks!

**Comment by Kennyc1012** [comment]
Looking at the code briefly, I don't seem to be injecting into the SettingsFragment. Might be a simple 1 line fix. I can take a look at it sometime this week.

**Comment by Kennyc1012** [comment]
Fixed with b5601744536815d4f0995c54620c92c9e7b72a99

**Comment by 1gn1t10n** [comment]
Thanks for the quick answer! I confirm that the settings work now.

Nothing is displayed, though. The only relevant messages I see are
```
W GCoreFlp: No location to return for getLastLocation()
W dashclock_WeatherExten: Stale or missing last-known location; requesting single location update.
W GCoreFlp: No location to return for getLastLocation()
```

They seem to be coming from DashClock. Location is enabled, it works fine in other applications like OsmAnd. The permissions are enabled for both DashClock and DashWeather. It is not a widget size issue, there is enough space to show other content. I'll keep investigating on my side as it is a different issue than the property initialization.

**Comment by Kennyc1012** [comment]
The location getting can be a little wonky sometimes. What I usually do is open Google Maps and press the icon to acquire my location. Once it does that, force a refresh of the widget (press it) and it should work.
